spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibernate-ex
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
server:
  port: 9393
