spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:

# для запуска в docker
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# для запуска локально
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/hibernate-ex
#    username: postgres
#    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true

server:
  port: 9393
